export const SERVICE_TOKENS = {
  REGISTER_DEVICE: Symbol('RegisterDeviceService'),
  GET_DEVICE: Symbol('GetDeviceService'),
  LIST_DEVICES: Symbol('ListDevicesService'),
  CREATE_USER: Symbol('CreateUserService'),
  PROCESS_POWER_STATUS: Symbol('ProcessPowerStatusService'),
  GET_POWER_HISTORY: Symbol('GetPowerHistoryService'),
  LINK_DEVICE_TO_USER: Symbol('LinkDeviceToUserService'),
  UPDATE_DEVICE: Symbol('UpdateDeviceService'),
  DELETE_DEVICE: Symbol('DeleteDeviceService'),
  ROTATE_DEVICE_SECRET: Symbol('RotateDeviceSecretService'),
  REQUEST_OTA_FORCE_CHECK: Symbol('RequestOtaForceCheckService'),
  UNLINK_DEVICE_FROM_USER: Symbol('UnlinkDeviceFromUserService'),
  LIST_USERS: Symbol('ListUsersService'),
  CHECK_OTA_UPDATE: Symbol('CheckOtaUpdateService'),
  UPLOAD_FIRMWARE: Symbol('UploadFirmwareService'),
  LIST_FIRMWARE_RELEASES: Symbol('ListFirmwareReleasesService'),
  GET_USER_DEVICES_OVERVIEW: Symbol('GetUserDevicesOverviewService'),
  GET_DEVICE_NOTIFICATION_RECIPIENTS: Symbol(
    'GetDeviceNotificationRecipientsService',
  ),
  UPDATE_USER_SETTINGS: Symbol('UpdateUserSettingsService'),
} as const;
